//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillsManager.Views.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BillsManager.Views.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,00:N2} €.
        /// </summary>
        public static string _currency_format {
            get {
                return ResourceManager.GetString("_currency_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z]*$.
        /// </summary>
        public static string _onlyLetters_regex {
            get {
                return ResourceManager.GetString("_onlyLetters_regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9]*$.
        /// </summary>
        public static string _onlyNumbers_regex {
            get {
                return ResourceManager.GetString("_onlyNumbers_regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rollbacks.
        /// </summary>
        public static string _rollbacksCount_format {
            get {
                return ResourceManager.GetString("_rollbacksCount_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy}.
        /// </summary>
        public static string _shortDate_format {
            get {
                return ResourceManager.GetString("_shortDate_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi fattura.
        /// </summary>
        public static string AddBill {
            get {
                return ResourceManager.GetString("AddBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiunta fattura fallita.
        /// </summary>
        public static string AddBillFailed {
            get {
                return ResourceManager.GetString("AddBillFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile aggiungere la fattura.
        /// </summary>
        public static string AddBillFailedMessage {
            get {
                return ResourceManager.GetString("AddBillFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spese.
        /// </summary>
        public static string AdditionalCosts {
            get {
                return ResourceManager.GetString("AdditionalCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi fornitore.
        /// </summary>
        public static string AddSupplier {
            get {
                return ResourceManager.GetString("AddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiunta fornitore fallita.
        /// </summary>
        public static string AddSupplierFailed {
            get {
                return ResourceManager.GetString("AddSupplierFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile aggiungere il fornitore.
        /// </summary>
        public static string AddSupplierFailedMessage {
            get {
                return ResourceManager.GetString("AddSupplierFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome agente.
        /// </summary>
        public static string AgentName {
            get {
                return ResourceManager.GetString("AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono agente.
        /// </summary>
        public static string AgentPhone {
            get {
                return ResourceManager.GetString("AgentPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenti.
        /// </summary>
        public static string Agents {
            get {
                return ResourceManager.GetString("Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome agente.
        /// </summary>
        public static string AgentSurname {
            get {
                return ResourceManager.GetString("AgentSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggio.
        /// </summary>
        public static string Agio {
            get {
                return ResourceManager.GetString("Agio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutte.
        /// </summary>
        public static string All_toBills {
            get {
                return ResourceManager.GetString("All_toBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutte le fatture.
        /// </summary>
        public static string AllTheBills {
            get {
                return ResourceManager.GetString("AllTheBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importo.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi specificare un importo.
        /// </summary>
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro Backup.
        /// </summary>
        public static string BackupCenter {
            get {
                return ResourceManager.GetString("BackupCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        public static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fattura.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli fattura.
        /// </summary>
        public static string BillDetails {
            get {
                return ResourceManager.GetString("BillDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatture.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills Manager.
        /// </summary>
        public static string BillsManager {
            get {
                return ResourceManager.GetString("BillsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla aggiunta.
        /// </summary>
        public static string CancelAdd {
            get {
                return ResourceManager.GetString("CancelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla modifiche.
        /// </summary>
        public static string CancelEdit {
            get {
                return ResourceManager.GetString("CancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non uscire.
        /// </summary>
        public static string CancelExit {
            get {
                return ResourceManager.GetString("CancelExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile superare i {1} caratteri.
        /// </summary>
        public static string CannotExceedChars_format {
            get {
                return ResourceManager.GetString("CannotExceedChars_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi inserire almeno {0} caratteri.
        /// </summary>
        public static string CannotStayBelowChars_format {
            get {
                return ResourceManager.GetString("CannotStayBelowChars_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ci sono delle modifiche non salvate.
        /// </summary>
        public static string ChangesNotSavedMessage {
            get {
                return ResourceManager.GetString("ChangesNotSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Città.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi dopo l&apos;invio.
        /// </summary>
        public static string CloseAfterSend {
            get {
                return ResourceManager.GetString("CloseAfterSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler effettuare il rollback al seguente backup?.
        /// </summary>
        public static string ConfirmRollbackQuestion {
            get {
                return ResourceManager.GetString("ConfirmRollbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connetti.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connetti automaticamente.
        /// </summary>
        public static string ConnectAutomatically {
            get {
                return ResourceManager.GetString("ConnectAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connesso.
        /// </summary>
        public static string Connected_toDB {
            get {
                return ResourceManager.GetString("Connected_toDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatti.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia eMail.
        /// </summary>
        public static string CopyEmail {
            get {
                return ResourceManager.GetString("CopyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paese.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea backup.
        /// </summary>
        public static string CreateBackup {
            get {
                return ResourceManager.GetString("CreateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler creare un nuovo backup?.
        /// </summary>
        public static string CreateBackupQuestion {
            get {
                return ResourceManager.GetString("CreateBackupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditore.
        /// </summary>
        public static string Creditor {
            get {
                return ResourceManager.GetString("Creditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditore.
        /// </summary>
        public static string Creditor_toSupplier {
            get {
                return ResourceManager.GetString("Creditor_toSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditori.
        /// </summary>
        public static string Creditor_toSuppliers {
            get {
                return ResourceManager.GetString("Creditor_toSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critico.
        /// </summary>
        public static string Critical_toDueAlert {
            get {
                return ResourceManager.GetString("Critical_toDueAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile connettersi database.
        /// </summary>
        public static string DatabaseConnectionFailed {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile connettersi al database.
        /// </summary>
        public static string DatabaseConnectionFailedMessage {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile salvare database.
        /// </summary>
        public static string DatabaseSaveFailed {
            get {
                return ResourceManager.GetString("DatabaseSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile salvare il database.
        /// </summary>
        public static string DatabaseSaveFailedMessage {
            get {
                return ResourceManager.GetString("DatabaseSaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi specificare una data.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debitore.
        /// </summary>
        public static string Debtor {
            get {
                return ResourceManager.GetString("Debtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debitore.
        /// </summary>
        public static string Debtor_toSupplier {
            get {
                return ResourceManager.GetString("Debtor_toSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debitori.
        /// </summary>
        public static string Debtor_toSuppliers {
            get {
                return ResourceManager.GetString("Debtor_toSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina backup.
        /// </summary>
        public static string DeleteBackup {
            get {
                return ResourceManager.GetString("DeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi davvero eliminare questo backup?.
        /// </summary>
        public static string DeleteBackupQuestion {
            get {
                return ResourceManager.GetString("DeleteBackupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina fattura.
        /// </summary>
        public static string DeleteBill {
            get {
                return ResourceManager.GetString("DeleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare questa fattura?.
        /// </summary>
        public static string DeleteBillQuestion {
            get {
                return ResourceManager.GetString("DeleteBillQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina fornitore.
        /// </summary>
        public static string DeleteSupplier {
            get {
                return ResourceManager.GetString("DeleteSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare questo fornitore?.
        /// </summary>
        public static string DeleteSupplierQuestion {
            get {
                return ResourceManager.GetString("DeleteSupplierQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler annullare tutte le modifiche?.
        /// </summary>
        public static string DiscardChangesQuestion {
            get {
                return ResourceManager.GetString("DiscardChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnetti.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnesso.
        /// </summary>
        public static string Disconnected_toDB {
            get {
                return ResourceManager.GetString("Disconnected_toDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtra.
        /// </summary>
        public static string DoFilter {
            get {
                return ResourceManager.GetString("DoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non salvare.
        /// </summary>
        public static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scadenza.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di scadenza.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaduta il.
        /// </summary>
        public static string DuedOn_toBill {
            get {
                return ResourceManager.GetString("DuedOn_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scadute il.
        /// </summary>
        public static string DuedOn_toBills {
            get {
                return ResourceManager.GetString("DuedOn_toBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scade il.
        /// </summary>
        public static string DuesOn {
            get {
                return ResourceManager.GetString("DuesOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica fattura.
        /// </summary>
        public static string EditBill {
            get {
                return ResourceManager.GetString("EditBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile modificare.
        /// </summary>
        public static string EditFailed {
            get {
                return ResourceManager.GetString("EditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il salvataggio delle modifiche.
        /// </summary>
        public static string EditFailedMessage {
            get {
                return ResourceManager.GetString("EditFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica fornitore.
        /// </summary>
        public static string EditSupplier {
            get {
                return ResourceManager.GetString("EditSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatario feedback.
        /// </summary>
        public static string FeedbackAddressee {
            get {
                return ResourceManager.GetString("FeedbackAddressee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback non inviato.
        /// </summary>
        public static string FeedbackNotSent {
            get {
                return ResourceManager.GetString("FeedbackNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile inviare il feedback.
        /// </summary>
        public static string FeedbackNotSentMessage {
            get {
                return ResourceManager.GetString("FeedbackNotSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback inviato.
        /// </summary>
        public static string FeedbackSent {
            get {
                return ResourceManager.GetString("FeedbackSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il tuo feedback è stato inviato.
        /// </summary>
        public static string FeedbackSentMessage {
            get {
                return ResourceManager.GetString("FeedbackSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtri.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trova.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartella.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confermo.
        /// </summary>
        public static string IConfirm {
            get {
                return ResourceManager.GetString("IConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basso.
        /// </summary>
        public static string Low_toDueAlert {
            get {
                return ResourceManager.GetString("Low_toDueAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio.
        /// </summary>
        public static string Medium_toDueAlert {
            get {
                return ResourceManager.GetString("Medium_toDueAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaggio.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellulare.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi inserire {0} caratteri.
        /// </summary>
        public static string MustBeNChars_format {
            get {
                return ResourceManager.GetString("MustBeNChars_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi inserire tra {0} e {1} caratteri.
        /// </summary>
        public static string MustStayWithinChars_format {
            get {
                return ResourceManager.GetString("MustStayWithinChars_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi specificare un nome.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova.
        /// </summary>
        public static string New_toBill {
            get {
                return ResourceManager.GetString("New_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo.
        /// </summary>
        public static string New_toSupplier {
            get {
                return ResourceManager.GetString("New_toSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo backup.
        /// </summary>
        public static string NewBackup {
            get {
                return ResourceManager.GetString("NewBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova fattura.
        /// </summary>
        public static string NewBill {
            get {
                return ResourceManager.GetString("NewBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo fornitore.
        /// </summary>
        public static string NewSupplier {
            get {
                return ResourceManager.GetString("NewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun backup disponibile.
        /// </summary>
        public static string NoBackupsAvailable {
            get {
                return ResourceManager.GetString("NoBackupsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullo.
        /// </summary>
        public static string None_toDueAlert {
            get {
                return ResourceManager.GetString("None_toDueAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non pagata.
        /// </summary>
        public static string NotPaid_toBill {
            get {
                return ResourceManager.GetString("NotPaid_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non pagate.
        /// </summary>
        public static string NotPaid_toBills {
            get {
                return ResourceManager.GetString("NotPaid_toBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obbligazione.
        /// </summary>
        public static string Obligation {
            get {
                return ResourceManager.GetString("Obligation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apri cartella dei backups.
        /// </summary>
        public static string OpenBackupsFolder {
            get {
                return ResourceManager.GetString("OpenBackupsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa operazione potrebbe richiedere del tempo.
        /// </summary>
        public static string OperationMayTakeAWhile {
            get {
                return ResourceManager.GetString("OperationMayTakeAWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scade tra {0} giorni.
        /// </summary>
        public static string OverduesInXDays_toBill_format {
            get {
                return ResourceManager.GetString("OverduesInXDays_toBill_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scade oggi.
        /// </summary>
        public static string OverduesToday_toBill {
            get {
                return ResourceManager.GetString("OverduesToday_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scade domani.
        /// </summary>
        public static string OverduesTomorrow_toBill {
            get {
                return ResourceManager.GetString("OverduesTomorrow_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaduta {0} giorni fa.
        /// </summary>
        public static string OverdueXDaysAgo_toBill_format {
            get {
                return ResourceManager.GetString("OverdueXDaysAgo_toBill_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaduta ieri.
        /// </summary>
        public static string OverdueYesterday_toBill {
            get {
                return ResourceManager.GetString("OverdueYesterday_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagato.
        /// </summary>
        public static string Paid_Male {
            get {
                return ResourceManager.GetString("Paid_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagata.
        /// </summary>
        public static string Paid_toBill {
            get {
                return ResourceManager.GetString("Paid_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagate.
        /// </summary>
        public static string Paid_toBills {
            get {
                return ResourceManager.GetString("Paid_toBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagata il.
        /// </summary>
        public static string PaidOn_toBill {
            get {
                return ResourceManager.GetString("PaidOn_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paga.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paga fattura.
        /// </summary>
        public static string PayBill {
            get {
                return ResourceManager.GetString("PayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler pagare questa fattura?.
        /// </summary>
        public static string PayBillQuestion {
            get {
                return ResourceManager.GetString("PayBillQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di pagamento.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa report.
        /// </summary>
        public static string PrintReport {
            get {
                return ResourceManager.GetString("PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrata il.
        /// </summary>
        public static string RegisteredOn_toBill {
            get {
                return ResourceManager.GetString("RegisteredOn_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione.
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilascio.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilasciata.
        /// </summary>
        public static string Released_toBill {
            get {
                return ResourceManager.GetString("Released_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di rilascio.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi specificare una data di rilascio.
        /// </summary>
        public static string ReleaseDateRequired {
            get {
                return ResourceManager.GetString("ReleaseDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilasciata il.
        /// </summary>
        public static string ReleasedOn_toBill {
            get {
                return ResourceManager.GetString("ReleasedOn_toBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilasciate il.
        /// </summary>
        public static string ReleasedOn_toBills {
            get {
                return ResourceManager.GetString("ReleasedOn_toBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback annullato.
        /// </summary>
        public static string RollbackCanceled {
            get {
                return ResourceManager.GetString("RollbackCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il rollback è stato annullato.
        /// </summary>
        public static string RollbackCanceledMessage {
            get {
                return ResourceManager.GetString("RollbackCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback completato.
        /// </summary>
        public static string RollbackCompleted {
            get {
                return ResourceManager.GetString("RollbackCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il rollback è stato completato!.
        /// </summary>
        public static string RollbackCompletedMessage {
            get {
                return ResourceManager.GetString("RollbackCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback fallito.
        /// </summary>
        public static string RollbackFailed {
            get {
                return ResourceManager.GetString("RollbackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile completare il rollback.
        /// </summary>
        public static string RollbackFailedMessage {
            get {
                return ResourceManager.GetString("RollbackFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva ed esci.
        /// </summary>
        public static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desideri salvare prima di uscire?.
        /// </summary>
        public static string SaveBeforeClosingQuestion {
            get {
                return ResourceManager.GetString("SaveBeforeClosingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desideri salvare?.
        /// </summary>
        public static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra tutto.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra fatture.
        /// </summary>
        public static string ShowBills {
            get {
                return ResourceManager.GetString("ShowBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oggetto.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornitore.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli fornitore.
        /// </summary>
        public static string SupplierDetails {
            get {
                return ResourceManager.GetString("SupplierDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi selezionare un fornitore.
        /// </summary>
        public static string SupplierRequired {
            get {
                return ResourceManager.GetString("SupplierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornitori.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riprova.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svincolata.
        /// </summary>
        public static string Unbound_toSupplier {
            get {
                return ResourceManager.GetString("Unbound_toSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svincolati.
        /// </summary>
        public static string Undound_toSuppliers {
            get {
                return ResourceManager.GetString("Undound_toSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non salvato.
        /// </summary>
        public static string Unsaved_toDB {
            get {
                return ResourceManager.GetString("Unsaved_toDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sito web.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAP.
        /// </summary>
        public static string ZIP {
            get {
                return ResourceManager.GetString("ZIP", resourceCulture);
            }
        }
    }
}
